### ISSUE TITLE
Need information about training data and base model

### ISSUE THREAD

**Issue by mohammadaaftabv** [QuoQA-NLP/T5_Translation#3]
Need information about base model used to train this. Is this model trained from scratch on the data mentioned? Or was the dataset mentioned in this repo used to finetune any existing model? If so, can I please get the name of the baseline model used? Also, how exactly was the dataset downloaded? Dataset link https://aihub.or.kr/aihub-data/natural-language/about given in https://github.com/snoop2head/Deep-Encoder-Shallow-Decoder?tab=readme-ov-file#dataset throws no URL found/404 error.
Can I please get information? Thanks.

**Comment by snoop2head** [comment]
@mohammadaaftabv 
Thank you for your interest in this project. Yes, it is trained from scratch. It seems like the url has been changed, so I will leave here the link for the dataset that I've used. 

- https://aihub.or.kr/aihubdata/data/view.do?currMenu=115&topMenu=100&aihubDataSe=data&dataSetSn=111
- https://aihub.or.kr/aihubdata/data/view.do?currMenu=115&topMenu=100&aihubDataSe=data&dataSetSn=124
- https://aihub.or.kr/aihubdata/data/view.do?currMenu=115&topMenu=100&aihubDataSe=data&dataSetSn=125
- https://aihub.or.kr/aihubdata/data/view.do?currMenu=115&topMenu=100&aihubDataSe=data&dataSetSn=126

**Comment by mohammadaaftabv** [comment]
Awesome thanks a lot!
